---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-helmchart
        namespace: flux-system
  values:
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 10.0.1.1-10.0.1.3