apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: simple-comment-section-source
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: master
  url: https://github.com/yungen-lu/simple-comment-section
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: simple-comment-section
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: simple-comment-section-source
  path: ./kustomize
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: simple-comment-section-registry
  namespace: flux-system
spec:
  image: yungen/simple-comment-section
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: simple-comment-section-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: simple-comment-section-registry
  policy:
    semver:
      range: >=1.0.0