apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: simple-comment-section-source
spec:
  interval: 5m0s
  ref:
    branch: main
  url: https://github.com/yungen-lu/simple-comment-section
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: simple-comment-section
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: simple-comment-section-source
  path: ./kustomize
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg