apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rbac.yaml
- helm-release.yaml
# - storage
- rook-ceph-tools
# - rook-direct-mount
# - service-monitors
# - snapshot-controller
# - dashboard