---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 3.32.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-helmchart
        namespace: flux-system
  values:
    controller:
      dnsPolicy: ClusterFirstWithHostNet
      reportNodeInternalIp: true
      hostNetwork: true
      hostPort:
        enabled: true
        ports:
          http: 80
          https: 443
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Equal
        effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      service:
        enabled: false
