---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 3.32.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-helmchart
        namespace: flux-system
  values:
    controller:
      service:
        type: LoadBalancer
        externalTrafficPolicy: Local
      autoscaling:
        enabled: false
    defaultBackend:
      enabled: false